// Extracts the static data tables from the website's browser assets and emits
// a clean ESM module (src/engine/data.js). This keeps the MCP server's results
// byte-identical to the live site and documents exactly where the data comes from.
//
// Run from mcp-server/:  node scripts/extract-data.mjs
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const assets = resolve(here, "../../assets");

// name => source file. Order matters only for readability of the output.
const TARGETS = [
  ["DOUBLE_SURNAMES", "name-engine.js"],
  ["WUXING_BY_TAIL", "name-engine.js"],
  ["SHENG", "name-engine.js"],
  ["KE", "name-engine.js"],
  ["GAN_ELEMENT", "name-engine.js"],
  ["ZHI_ELEMENT", "name-engine.js"],
  ["KANGXI_STROKES", "name-engine.js"],
  ["ZHI_HIDDEN", "name-engine.js"],
  ["CHAR_ELEMENT_HINTS", "name-engine.js"],
  ["INDUSTRIES", "company-name-test.js"],
  ["LEVELS", "company-name-test.js"],
  ["NUMEROLOGY", "company-name-test.js"],
  ["COMMON_STROKES", "company-name-test.js"],
];

// Pull `const NAME = <literal>;` out of source text using bracket-depth scanning
// that respects string/comment context so braces inside strings never miscount.
function extractConst(src, name) {
  const decl = new RegExp(`const\\s+${name}\\s*=`);
  const m = decl.exec(src);
  if (!m) throw new Error(`could not find: const ${name}`);
  let i = m.index + m[0].length;
  // skip whitespace to the opening bracket
  while (i < src.length && /\s/.test(src[i])) i++;
  const open = src[i];
  if (open !== "{" && open !== "[") throw new Error(`${name}: unexpected start '${open}'`);
  const close = open === "{" ? "}" : "]";
  let depth = 0;
  let str = null; // current string quote char, or null
  let out = "";
  for (; i < src.length; i++) {
    const ch = src[i];
    out += ch;
    if (str) {
      if (ch === "\\") { out += src[++i]; continue; } // escaped char
      if (ch === str) str = null;
      continue;
    }
    if (ch === '"' || ch === "'" || ch === "`") { str = ch; continue; }
    if (ch === open) depth++;
    else if (ch === close) {
      depth--;
      if (depth === 0) break;
    }
  }
  return out;
}

const sources = {};
function load(file) {
  if (!sources[file]) sources[file] = readFileSync(resolve(assets, file), "utf8");
  return sources[file];
}

let body = `// AUTO-GENERATED by scripts/extract-data.mjs — do not edit by hand.
// Source of truth: ../../assets/name-engine.js and ../../assets/company-name-test.js
// Regenerate after changing the site's data tables.
`;
for (const [name, file] of TARGETS) {
  const literal = extractConst(load(file), name);
  body += `\nexport const ${name} = ${literal};\n`;
}

const outPath = resolve(here, "../src/engine/data.js");
writeFileSync(outPath, body, "utf8");
console.log(`wrote ${outPath} (${TARGETS.length} tables)`);

// Sync the big shared Kangxi table (assets/kangxi-strokes.js, produced by build-kangxi.mjs)
// into its own engine module so strokes.js can import it. Empty stub if not built yet.
const kxPath = resolve(assets, "kangxi-strokes.js");
const kxOut = resolve(here, "../src/engine/kangxi-db.js");
let kxLiteral = "{}";
let kxCount = 0;
if (existsSync(kxPath)) {
  kxLiteral = extractConst(readFileSync(kxPath, "utf8"), "KANGXI_DB");
  kxCount = (kxLiteral.match(/:/g) || []).length;
}
writeFileSync(kxOut, `// AUTO-GENERATED by scripts/extract-data.mjs from ../../assets/kangxi-strokes.js\nexport const KANGXI_DB = ${kxLiteral};\n`, "utf8");
console.log(`wrote ${kxOut} (${kxCount} chars)`);

// Vendor the site's name engine verbatim so the MCP can execute it in a sandbox —
// guarantees the MCP's name scoring stays byte-identical to the website (no port drift).
const neSrc = readFileSync(resolve(assets, "name-engine.js"), "utf8");
const neOut = resolve(here, "../src/engine/site-name-engine.js");
writeFileSync(neOut, `// AUTO-GENERATED copy of ../../assets/name-engine.js — do not edit by hand. Regenerate with extract-data.\n${neSrc}`, "utf8");
console.log(`wrote ${neOut} (vendored site name engine)`);
